name: Bergie Today
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5dc0c9fe-61bd-4213-bd6a-513b80e78904.png
layout_spectrum: 0.44816
typography_spectrum: 0.78264
cta: {}
analytics:
  google: UA-75936-17
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#080000'
    - '#f6cc9e'
    - '#bf956d'
    - '#411d0d'
    - '#926b4a'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
title: Henri Bergius
Description: Daily Linklog
author:
  name: Henri Bergius
  url: 'http://bergie.iki.fi'
  email: henri.bergius@iki.fi
content_rating:
  adult: false
