name: Bergie
favicon: null
layout_spectrum: 0.23756
typography_spectrum: 0.78264
title: Henri Bergius
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75936-17
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080000'
    - '#f6cc9e'
    - '#bf956d'
    - '#411d0d'
    - '#926b4a'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
